spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: telegram-assistant-bot
  codec:
    max-in-memory-size-mb: 250
  datasource:
    userdb:
      jdbc-url: ${USER_DB_URL}
      url: ${USER_DB_URL}
      driverClassName: org.postgresql.Driver
      username: ${USER_DB_USERNAME}
      password: ${USER_DB_PASSWORD}
      table-scheme: ${USER_DB_TABLE_SCHEME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
  file:
    path: logs
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: ${PORT_NUMBER}

kafka:
  bootstrap-url: ${KAFKA_BOOTSTRAP_URL}
  group: ${KAFKA_GROUP_ID}
  topic:
    request: ${KAFKA_REQUEST_TOPIC_NAME}
    response: ${KAFKA_RESPONSE_TOPIC_NAME}

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  max-message-length: ${BOT_MAX_MESSAGE_LENGTH:4000}

telegram-api:
  base-url: ${TELEGRAM_API_BASE_URL}

file-repository:
  base-url: ${S3_BASE_URL}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket-name: ${S3_BUCKET_NAME}